# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NEO Davidshall
tagline: Gamla polishuset i Malmö
author: Styrelsen
email: styrelsen@neodavidshall.org
description: >- # this means to ignore newlines until "baseurl:"
  NEO Davidshall är en bostadsrättsförening som ligger belägen mitt i Malmös
  centrum intill Davidshallstorg.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.neodavidshall.org" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/logo.png
google_analytics: G-QDEHC5T7HR

# Build settings
theme: minima
# remote_theme: vvalchev/creative-theme-jekyll-new
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-responsive-image

responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 750
    - width: 1080
    - width: 1366
    - width: 1920
  strip: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
